version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/springboot-app
  production:
    image: ${DOCKER_USER_ID}/springboot-app:${BUILD_NUMBER}
    container_name: springboot-app
    ports:
      - '8081:8081'
    environment:
      - "SPRING_PROFILES_ACTIVE=prd"
